Add openrazer-daemon
Preinstalls the drivers and deamons for razer hardware.

Closes #416

diff --git a/mkosi.extra/usr/lib/rebuild-efi b/mkosi.extra/usr/lib/rebuild-efi
--- a/mkosi.extra/usr/lib/rebuild-efi
+++ b/mkosi.extra/usr/lib/rebuild-efi
@@ -18,6 +18,13 @@ if [ -z "$kernel_version" ]; then
   exit 1
 fi
 
+# Ensure all DKMS modules are built for this kernel before we generate the initramfs
+if ! dkms autoinstall -k "$kernel_version"; then
+        echo "Error: DKMS autoinstall failed" >&2
+        exit 1
+fi
+
+
 # NOTE: plymouth MUST be after systemd as per the wiki!
 cat <<- EOF > mkinitcpio.conf
 MODULES=(overlay)
