style++

diff --git a/mkosi.extra/usr/lib/rebuild-efi b/mkosi.extra/usr/lib/rebuild-efi
--- a/mkosi.extra/usr/lib/rebuild-efi
+++ b/mkosi.extra/usr/lib/rebuild-efi
@@ -20,10 +20,9 @@ fi
 
 # Ensure all DKMS modules are built for this kernel before we generate the initramfs
 if ! dkms autoinstall -k "$kernel_version"; then
-        echo "Error: DKMS autoinstall failed" >&2
-        exit 1
+  echo "Error: DKMS autoinstall failed" >&2
+  exit 1
 fi
-
 
 # NOTE: plymouth MUST be after systemd as per the wiki!
 cat <<- EOF > mkinitcpio.conf
